#default controller
user_default_profile:
    pattern:  /userprofile
    defaults: { _controller: ydzyUserBundle:Default:profile }

user_default_login:
    pattern:  /userlogin
    defaults: { _controller: ydzyUserBundle:Default:login }

user_default_gettoken:
    pattern:  /gettoken
    defaults: { _controller: ydzyUserBundle:Default:GetToken }


    
user_default_sendvalidate:
    pattern:  /usersendvalidate
    defaults: { _controller: ydzyUserBundle:Default:sendValidate }
    
user_default_register:
    pattern:  /userregister
    defaults: { _controller: ydzyUserBundle:Default:register }
    
user_default_changepassword:
    pattern:  /userchangepassword
    defaults: { _controller: ydzyUserBundle:Default:changepassword }

user_default_cuserinfo:
    pattern:  /cuserinfo
    defaults: { _controller: ydzyUserBundle:Default:cuserinfo }


#user controller
ydzy_create_user:
    pattern:  /user/create
    defaults: { _controller: ydzyUserBundle:User:create }
    
ydzy_retrieve_user:
    pattern:  /user/retrieve
    defaults: { _controller: ydzyUserBundle:User:retrieve }    
    
ydzy_list_user:
    pattern:  /user/list
    defaults: { _controller: ydzyUserBundle:User:list }    
    
ydzy_edit_user:
    pattern:  /user/edit
    defaults: { _controller: ydzyUserBundle:User:edit }    
    
ydzy_delete_user:
    pattern:  /user/delete
    defaults: { _controller: ydzyUserBundle:User:delete }    
    
ydzy_login_user:
    pattern:  /user/login
    defaults: { _controller: ydzyUserBundle:User:login }  
ydzy_logout_user:
    pattern:  /user/logout
    defaults: { _controller: ydzyUserBundle:User:logout }
ydzy_cuserinfo_user:
    pattern:  /user/cuserinfo
    defaults: { _controller: ydzyUserBundle:User:cuserinfo }





#fosuserbundle    
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile